server:
  port: 9191
  servlet:
    context-path: /auth-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true
    username: [username]
    password: [password]
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  application:
    name: auth-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: -*
        exclude: env,beans
    